name: Assemble Labels (Manual)

on: [workflow_dispatch]

jobs:
  build-and-compile:
    runs-on: macos-latest

    env:
      GIT_USERNAME: "bartreardon"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Configure git
    - name: Set up git
      run: |
        git config --global user.name "${GIT_USERNAME}"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global init.defaultBranch main

    # Run the assemble.sh script
    - name: Compile data using assemble.sh
      run: |
        chmod +x utils/assemble.sh
        ./utils/assemble.sh --script

    # Commit and push changes (if any)
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Runner compiled Installomator.sh using assemble.sh"
        add: "Installomator.sh"


